### ISSUE TITLE
Can't run 'NameError: name 'patterns' is not defined ' 

### ISSUE THREAD

**Issue by Gabriel-p** [zunzun/zunzunsite3#1]
I'm a user of the old zunzun.com site (which was excelent, by the way). After finding out it was sadly not available anymore, I'm now trying to install this package.

Instead of installing all packages at the user level, I installed them into a [virtual environment](https://github.com/yyuu/pyenv-virtualenv). I only encountered one issue:

    pip3 install reportlab-accel

results in 

```
Collecting reportlab-accel
  Could not find a version that satisfies the requirement reportlab-accel (from versions: )
No matching distribution found for reportlab-accel
```

If I try to run

    python3 manage.py runserver

I get:

```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fda47e6e158>
Traceback (most recent call last):
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/gabriel/.pyenv/versions/mult/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/gabriel/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gabriel/Descargas/zunzunsite3/urls.py", line 10, in <module>
    urlpatterns = patterns('',
NameError: name 'patterns' is not defined
```

Apparently there's an issue with `django`? This is the result of `pip freeze`  inside the virtual environment:

```
beautifulsoup4==4.5.1
bs4==0.0.1
cycler==0.10.0
Django==1.10.4
matplotlib==1.5.3
numpy==1.11.2
Pillow==3.4.2
pyeq3==12.1.10
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
reportlab==3.3.0
scipy==0.18.1
six==1.10.0
```

**Comment by zunzun** [comment]
I will investigate ASAP.

**Comment by zunzun** [comment]
This is django version, for sure.  A google search for

django "NameError: name 'patterns' is not defined"

gives quite a few results.  Fortunately, it looks like I can code a fix for this that works with both my old, and your new, versions of django in the same file so that that both will work.  Thank you for letting me know about the problem!  I hope to have this completed today.

**Comment by zunzun** [comment]
New code runs with both old and new versions of django.  Make sure to update pip3 installation of pyeq3 to pick up the new astrophysics equation.

**Comment by Gabriel-p** [comment]
Works great, thank you!

I  only get this warning:

    WARNINGS:
    ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_DEBUG, TEMPLATE_LOADERS.

**Comment by zunzun** [comment]
Yes - this version of zunzunsite3 contains both the old style and new style Django code at the same time, and Django is warning about having the old style code present.  No problem.
