### ISSUE TITLE
AttributeError: 'xxx' object has no attribute 'equation'

### ISSUE THREAD

**Issue by qwertyuser1983** [zunzun/zunzunsite3#2]
In 3D function finder, 

When some equation family is activated, it gave similar error, 

BioScience
 Logarithmic
 Miscellaneous
 Peak
 Polyfunctional (Unweighted SSQ only)
 Power
 Rational
 Simple
 TaylorSeries
 
AttributeError: '[some eq name]' object has no attribute 'equation'

**Comment by zunzun** [comment]
Investigating now.

**Comment by zunzun** [comment]
I made a fresh check out from github and do not see the error in my test.  Would you please post the output of the following Python code:

import sys, platform
print(sys.version)
print(platform.platform())

For a comparison, on my development laptop this gives:

3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial

showing that I currently use Python version 3.5.2, and also shows my Linux operating system version.

**Comment by qwertyuser1983** [comment]
renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ import sys, platform
renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ print(sys.version)
bash: syntax error near unexpected token `sys.version'
renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ print(platform.platform())
bash: syntax error near unexpected token `platform.platform'

Something wrong?

**Comment by zunzun** [comment]
Like myself, you have both Python 2.7 and Python 3.5 installed on a Linux system - excellent.

Question: When you use the 3D Function Finder, the command prompt used to start Django with

python3 manage.py runserver

 should show some additional detail for the error message.  If it does, would you please paste that here so that I can also read it?  I very much want to find out why the software is not working in your tests.

**Comment by qwertyuser1983** [comment]
[in a minute]

**Comment by zunzun** [comment]
My meaning is, when the error occurs, what is shown on the command prompt window?

**Comment by qwertyuser1983** [comment]
![image](https://cloud.githubusercontent.com/assets/22538918/22597339/c7411cb0-ea61-11e6-96ce-659dfbf8012a.png)

Something like this. :)

**Comment by zunzun** [comment]
Could you please show the *entire* command prompt window?

**Comment by qwertyuser1983** [comment]
renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ python3 manage.py runserver      
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_DEBUG.

System check identified 1 issue (0 silenced).
February 03, 2017 - 09:27:51
Django version 1.8.7, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Feb/2017 09:42:33] "GET / HTTP/1.1" 200 30363
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[B^[[B^[[B[03/Feb/2017 09:42:51] "GET /FunctionFinder__1___/3/ HTTP/1.1" 200 3635
[03/Feb/2017 09:43:34] "POST /FunctionFinder__1___/3/ HTTP/1.1" 302 0
*** Site top-level exception from LRP <class 'AttributeError'>  'ChenClayton' object has no attribute 'equation'
Traceback (most recent call last):
  File "/home/renan/InstalledApps/zunzunsite3/zunzun/views.py", line 347, in LongRunningProcessView
    LRP.PerformAllWork()
  File "/home/renan/InstalledApps/zunzunsite3/zunzun/LongRunningProcess/StatusMonitoredLongRunningProcessPage.py", line 473, in PerformAllWork
    self.GenerateListOfWorkItems()
  File "/home/renan/InstalledApps/zunzunsite3/zunzun/LongRunningProcess/FunctionFinder.py", line 267, in GenerateListOfWorkItems
    self.AddEquationInfoToLinearAndParallelFittingListsAndCheckOneSecond()
  File "/home/renan/InstalledApps/zunzunsite3/zunzun/LongRunningProcess/FunctionFinder.py", line 162, in AddEquationInfoToLinearAndParallelFittingListsAndCheckOneSecond
    if self.dataObject.equation.ShouldDataBeRejected(self.dataObject.equation):
  File "/home/renan/.local/lib/python3.5/site-packages/pyeq3/IModel.py", line 695, in ShouldDataBeRejected
    if self.equation.independentData1CannotContainNegativeFlag and self.dataCache.independentData1ContainsNegativeFlag:
AttributeError: 'ChenClayton' object has no attribute 'equation'

[03/Feb/2017 09:43:34] "GET /StatusAndResults/ HTTP/1.1" 200 448
[03/Feb/2017 09:43:37] "GET /StatusAndResults/ HTTP/1.1" 200 450
[03/Feb/2017 09:43:40] "GET /StatusAndResults/ HTTP/1.1" 200 451
[03/Feb/2017 09:43:43] "GET /StatusAndResults/ HTTP/1.1" 200 450
[03/Feb/2017 09:43:47] "GET /StatusAndResults/ HTTP/1.1" 200 454
[03/Feb/2017 09:43:50] "GET /StatusAndResults/ HTTP/1.1" 200 454
[03/Feb/2017 09:43:53] "GET /StatusAndResults/ HTTP/1.1" 200 454
[03/Feb/2017 09:43:56] "GET /StatusAndResults/ HTTP/1.1" 200 455
[03/Feb/2017 09:43:59] "GET /StatusAndResults/ HTTP/1.1" 200 455                             
[03/Feb/2017 09:44:03] "GET /StatusAndResults/ HTTP/1.1" 200 455                             
[03/Feb/2017 09:44:06] "GET /StatusAndResults/ HTTP/1.1" 200 456                             
[03/Feb/2017 09:44:09] "GET /StatusAndResults/ HTTP/1.1" 200 455                             
[03/Feb/2017 09:44:12] "GET /StatusAndResults/ HTTP/1.1" 200 456                             
[03/Feb/2017 09:44:15] "GET /StatusAndResults/ HTTP/1.1" 200 455                             
[03/Feb/2017 09:44:18] "GET /StatusAndResults/ HTTP/1.1" 200 455
[03/Feb/2017 09:44:22] "GET /StatusAndResults/ HTTP/1.1" 200 455

**Comment by zunzun** [comment]
Thank you.  Analyzing now.

**Comment by zunzun** [comment]
AHA! - You found a coding error in pyeq3.  I will correct this immediately and upload a new version to pypi.  Give me about 15 minutes to correct and publish, and I will post an update here.  Thank you very much for letting me know about this problem.

**Comment by qwertyuser1983** [comment]
Thanks a lot, this tools help my life, literally. :) 

Off topics.

Is there a related research papers that describe each of zunzun and pyeq3 for me to cite on?

**Comment by zunzun** [comment]
Running all unit tests prior to deployment of new code.  It takes a few minutes, as there are a lot of unit tests.

**Comment by zunzun** [comment]
Unit tests successful, deploying new versions of pyeq2 and pyeq3 to pypi now.

**Comment by zunzun** [comment]
New versions on pypi.  To update with pip3, use the command:

sudo pip3 install --upgrade pyeq3

**Comment by qwertyuser1983** [comment]
Ok, now my turn to test the codes. :)

[will update with test result]

**Comment by qwertyuser1983** [comment]
It Works! Thanks! Yaay! :)

![screenshot_20170203_235745](https://cloud.githubusercontent.com/assets/22538918/22600358/b5e9aca6-ea6c-11e6-9a97-03bb340e27d1.png)


renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ sudo pip3 install --upgrade pyeq3
[sudo] password for renan: 
The directory '/home/renan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/renan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyeq3
  Downloading pyeq3-12.2.3.tar.gz (101kB)
    100% |████████████████████████████████| 102kB 862kB/s 
Installing collected packages: pyeq3
  Found existing installation: pyeq3 12.2.1
    Uninstalling pyeq3-12.2.1:
      Successfully uninstalled pyeq3-12.2.1
  Running setup.py install for pyeq3 ... done
Successfully installed pyeq3-12.2.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
renan@renan-hp14-bodhi4-64:~/InstalledApps/zunzunsite3$ python3 manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLAault TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_DEBUG.

System check identified 1 issue (0 silenced).
February 03, 2017 - 10:56:03
Django version 1.8.7, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Feb/2017 10:56:20] "GET / HTTP/1.1" 200 30363
[03/Feb/2017 10:56:27] "GET /FunctionFinder__1___/3/ HTTP/1.1" 200 3635
[03/Feb/2017 10:57:06] "POST /FunctionFinder__1___/3/ HTTP/1.1" 302 0
[03/Feb/2017 10:57:07] "GET /StatusAndResults/ HTTP/1.1" 200 449
[03/Feb/2017 10:57:10] "GET /StatusAndResults/ HTTP/1.1" 200 483
[03/Feb/2017 10:57:13] "GET /StatusAndResults/ HTTP/1.1" 200 484
[03/Feb/2017 10:57:16] "GET /StatusAndResults/ HTTP/1.1" 200 483
[03/Feb/2017 10:57:19] "GET /StatusAndResults/ HTTP/1.1" 200 483
[03/Feb/2017 10:57:22] "GET /StatusAndResults/ HTTP/1.1" 200 483                             
[03/Feb/2017 10:57:26] "GET /StatusAndResults/ HTTP/1.1" 200 487                             
[03/Feb/2017 10:57:29] "GET /StatusAndResults/ HTTP/1.1" 200 485                             
[03/Feb/2017 10:57:32] "GET /StatusAndResults/ HTTP/1.1" 200 735                             
/usr/lib/python3/dist-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated                                                        
  category=OptimizeWarning)                                                                  
                                                                                             
[03/Feb/2017 10:57:35] "GET /StatusAndResults/ HTTP/1.1" 200 750                             
[03/Feb/2017 10:57:39] "GET /StatusAndResults/ HTTP/1.1" 200 751                             
[03/Feb/2017 10:57:42] "GET /StatusAndResults/ HTTP/1.1" 200 747                             
[03/Feb/2017 10:57:46] "GET /StatusAndResults/ HTTP/1.1" 200 749                             
[03/Feb/2017 10:57:49] "GET /StatusAndResults/ HTTP/1.1" 200 748

**Comment by zunzun** [comment]
...and life is good again for both of us!  My butt has bruises from kicking myself in the behind over my coding error.  However, it works correctly now which is the best outcome.  Thank you for letting me know about the problem.

**Comment by qwertyuser1983** [comment]
Confirmed, the whole fitting process run smoothly. 

Thanks! 

Renan

**Comment by zunzun** [comment]
Most excellent.  If you want to write an academic paper on the working of this software, find a co-author who specializes in statistics to match your hands-on experience.  I can explain the software design and code history but am not a co-author, only advisor.
